### ISSUE TITLE
panic: makechan: size out of range, if used with -limit 1

### ISSUE THREAD

**Issue by MaxPeal** [goodwithtech/dockertags#22]
```
maxpeal@static:~$ docker run --rm goodwithtech/dockertags -limit 1 -format json aquasec/trivy | jq -r .[0].tags[0]
panic: makechan: size out of range

goroutine 1 [running]:
github.com/goodwithtech/dockertags/pkg/provider/dockerhub.(*DockerHub).Run(0xc000598200, 0xd792a0, 0xc000386c00, 0xc000214140, 0x9, 0xc00021414a, 0xd, 0xc00034b680, 0xc0002501a0, 0x0, ...)
        /go/src/github.com/goodwithtech/dockertags/pkg/provider/dockerhub/dockerhub.go:52 +0x299
github.com/goodwithtech/dockertags/pkg/provider.Exec(0x7ffc4ce93f62, 0xd, 0xc00034b680, 0xc0002501a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/goodwithtech/dockertags/pkg/provider/provider.go:39 +0x200
github.com/goodwithtech/dockertags/pkg.Run(0xc0003c8160, 0x0, 0x0)
        /go/src/github.com/goodwithtech/dockertags/pkg/run.go:43 +0x281
github.com/urfave/cli.HandleAction(0xac8fa0, 0xbeaab8, 0xc0003c8160, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.0/app.go:523 +0xbe
github.com/urfave/cli.(*App).Run(0xc0003e61c0, 0xc00001e1e0, 0x6, 0x6, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.0/app.go:285 +0x5df
main.main()
        /go/src/github.com/goodwithtech/dockertags/cmd/dockertags/main.go:87 +0x7c2
maxpeal@static:~$
```

but without -limit 1 it work:
```
maxpeal@static:~$ docker run --rm goodwithtech/dockertags -format json aquasec/trivy | jq -r .[0].tags[0]
latest
maxpeal@static:~$
```

**Comment by tomoyamachi** [comment]
@MaxPeal Thank you for the report. That bug fixed by #23.
